apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: nodeserver
  newName: rafaeljcamara/gitopsfc
  newTag: 2183152261152403daebbe59263f5ac8753825ac
