apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: nodeserver
  newName: rafaeljcamara/gitopsfc
  newTag: a7b7543ab450e19b54f3e80f1b455eaa623ac180
